# Generated by Django 3.2.9 on 2024-01-22 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDBArea',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBHostProduct',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBInstanceProduct',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBManufacturer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBMonitored',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBPrimaryfunction',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBSite',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBSox_relevance',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBStatus',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBUrgency',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMDBUsage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigMultipurpose',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('cmdbid', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('name', models.CharField(max_length=80)),
                ('dns', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^IF[0-9]{8}', 'invalid Global ID')])),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cmdbarea')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdbmanufacturer')),
                ('monitored', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cmdbmonitored')),
                ('primary_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdbprimaryfunction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdbhostproduct')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdbsite')),
                ('sox_relevance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cmdbsox_relevance')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdbstatus')),
                ('urgency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdburgency')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cmdbusage')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalHostParameter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('parameter_section', models.CharField(choices=[('cmdb', 'cmdb'), ('automation', 'automation'), ('contact', 'contact'), ('config', 'config'), ('license', 'license')], max_length=40)),
                ('parameter', models.CharField(choices=[('cmdb', (('ci_name', 'ci_name'), ('ci_description', 'ci_description'), ('serial_number', 'serial_number'), ('additional_information', 'additional_information'), ('tag_list', 'tag_list'), ('child_dependency', 'child_dependency'), ('supported_by_relation', 'supported_by_relation'), ('used_by_relation', 'used_by_relation'), ('eva_dependency', 'eva_dependency'), ('model_version', 'model_version'), ('lastupdate', 'lastupdate'))), ('automation', (('backupshare', 'backupshare'), ('script_set_version', 'script_set_version'), ('boostfs', 'boostfs'), ('hostgroup', 'hostgroup'))), ('license', (('type', 'type'), ('edition', 'edition')))], max_length=80)),
                ('parameter_index', models.IntegerField()),
                ('value', models.CharField(max_length=200, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_by', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.host')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical host parameter',
                'verbose_name_plural': 'historical host parameters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHost',
            fields=[
                ('cmdbid', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('name', models.CharField(max_length=80)),
                ('dns', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^IF[0-9]{8}', 'invalid Global ID')])),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_by', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbarea')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbmanufacturer')),
                ('monitored', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbmonitored')),
                ('primary_function', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbprimaryfunction')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbhostproduct')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbsite')),
                ('sox_relevance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbsox_relevance')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbstatus')),
                ('urgency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdburgency')),
                ('usage_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbusage')),
            ],
            options={
                'verbose_name': 'historical host',
                'verbose_name_plural': 'historical hosts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HostParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_section', models.CharField(choices=[('cmdb', 'cmdb'), ('automation', 'automation'), ('contact', 'contact'), ('config', 'config'), ('license', 'license')], max_length=40)),
                ('parameter', models.CharField(choices=[('cmdb', (('ci_name', 'ci_name'), ('ci_description', 'ci_description'), ('serial_number', 'serial_number'), ('additional_information', 'additional_information'), ('tag_list', 'tag_list'), ('child_dependency', 'child_dependency'), ('supported_by_relation', 'supported_by_relation'), ('used_by_relation', 'used_by_relation'), ('eva_dependency', 'eva_dependency'), ('model_version', 'model_version'), ('lastupdate', 'lastupdate'))), ('automation', (('backupshare', 'backupshare'), ('script_set_version', 'script_set_version'), ('boostfs', 'boostfs'), ('hostgroup', 'hostgroup'))), ('license', (('type', 'type'), ('edition', 'edition')))], max_length=80)),
                ('parameter_index', models.IntegerField()),
                ('value', models.CharField(max_length=200, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host')),
            ],
            options={
                'unique_together': {('fk', 'parameter_section', 'parameter', 'parameter_index')},
            },
        ),
    ]
