# Generated by Django 3.2.9 on 2024-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicalinstance_account_historicalinstance_accountparameter_instance_account_instance_accountpara'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstance_account',
            name='modified_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance_account',
            name='modified_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalinstance',
            name='address',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='address',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
