# Generated by Django 3.2.9 on 2024-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240122_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstanceparameter',
            name='parameter_section',
            field=models.CharField(choices=[('config', 'config'), ('contact', 'contact'), ('cmdb', 'cmdb')], max_length=40),
        ),
        migrations.AlterField(
            model_name='instanceparameter',
            name='parameter_section',
            field=models.CharField(choices=[('config', 'config'), ('contact', 'contact'), ('cmdb', 'cmdb')], max_length=40),
        ),
    ]
