# Generated by Django 3.2.9 on 2024-01-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240122_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstance_account',
            name='accountid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instance_account',
            name='accountid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
