# Generated by Django 3.2.9 on 2024-01-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cmdbdatabaseproduct_database_account_database_accountparameter_db_dbparameter_historicaldatabase_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='ci_description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db',
            name='ci_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db',
            name='serial_number',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbparameter',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicaldb',
            name='ci_description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldb',
            name='ci_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldb',
            name='serial_number',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldbparameter',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalinstance',
            name='ci_description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalinstance',
            name='ci_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalinstance',
            name='serial_number',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='ci_description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='ci_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='serial_number',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
    ]
