# Generated by Django 3.2.9 on 2024-01-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240124_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
