# Generated by Django 3.2.9 on 2024-01-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20240125_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhost',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
