# Generated by Django 3.2.9 on 2024-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240125_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='area',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='area',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
