# Generated by Django 3.2.9 on 2024-01-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20240125_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='sox_relevance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cmdbsox_relevance'),
        ),
    ]
