# Generated by Django 3.2.9 on 2024-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_host_sox_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhost',
            name='sox_relevance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='sox_relevance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
