# Generated by Django 3.2.9 on 2024-01-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20240125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhostparameter',
            name='parameter_section',
            field=models.CharField(choices=[('cmdb', 'cmdb'), ('config', 'config'), ('licenses', 'licenses')], max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalinstance',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinstance',
            name='sox_relevance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hostparameter',
            name='parameter_section',
            field=models.CharField(choices=[('cmdb', 'cmdb'), ('config', 'config'), ('licenses', 'licenses')], max_length=40),
        ),
        migrations.AlterField(
            model_name='instance',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='sox_relevance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
