# Generated by Django 3.2.9 on 2024-01-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20240126_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstance',
            name='monitored',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.cmdbmonitored'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='monitored',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='api.cmdbmonitored'),
        ),
    ]
