# Generated by Django 3.2.9 on 2024-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20240126_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstance_account',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='instance_account',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
