# Generated by Django 3.2.9 on 2024-01-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20240128_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldb',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
