# Generated by Django 3.2.9 on 2024-01-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20240129_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMDBArea',
        ),
        migrations.DeleteModel(
            name='CMDBSox_relevance',
        ),
    ]
