# Generated by Django 3.2.9 on 2024-01-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20240130_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_account',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldatabase_account',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
