# Generated by Django 3.2.9 on 2024-02-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20240130_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalhost',
            old_name='contact',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='contact',
            new_name='owner',
        ),
    ]
