# Generated by Django 3.2.9 on 2024-02-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20240202_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmultipurpose',
            name='name',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
