# Generated by Django 3.2.9 on 2024-02-08 02:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_alter_configmultipurpose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OraTablespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdbid', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('db_account', models.CharField(max_length=200)),
                ('tablespace_name', models.CharField(max_length=200)),
                ('tablespace_size', models.BigIntegerField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalOraTablespace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cmdbid', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('db_account', models.CharField(max_length=200)),
                ('tablespace_name', models.CharField(max_length=200)),
                ('tablespace_size', models.BigIntegerField()),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_by', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ora tablespace',
                'verbose_name_plural': 'historical ora tablespaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
