# Generated by Django 3.2.9 on 2024-02-08 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_historicaloratablespace_oratablespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloratablespace',
            name='cmdbid',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=15, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.db', validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')]),
        ),
        migrations.AlterField(
            model_name='oratablespace',
            name='cmdbid',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='api.db', validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')]),
        ),
    ]
